import Head from "next/head";
import { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { asyncReceiveHomeData } from "../states/shared/action";
import Carousel from "../components/Carousel";
import Category from "../components/Category";
import Layout from "../containers/Layout";
import LoadingLayout from "../containers/LoadingLayout";

export default function Home() {
  const { carousel = [], categories = [] } = useSelector((states) => states);

  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(asyncReceiveHomeData());
  }, [dispatch]);

  if (carousel.length === 0) {
    return <LoadingLayout />;
  }

  return (
    <>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout home>
        <Carousel data={carousel} />
        <Category data={categories} />
      </Layout>
    </>
  );
}
